### ISSUE TITLE
cli: `--outfile`

### ISSUE THREAD

**Issue by cpyle0819** [DavidSouther/ailly#62]
Feature request for `ailly --context folder --create my_file.js --prompt "Write a script to reverse a string."`

**Comment by DavidSouther** [comment]
Or why not shell redirection?

**Comment by cpyle0819** [comment]
That's a smart way to look at it. I could roll with this.

**Comment by DavidSouther** [comment]
I'll add an integration test; if there's an issue with logging, we can handle that separately.
